### ISSUE TITLE
Doesn't work with '3.5.2 |Anaconda 4.2.0 (x86_64)|

### ISSUE THREAD

**Issue by JJ0131** [seme0021/python-zillow#13]
Error message:
File "/Users/jianjin/anaconda/lib/python3.5/site-packages/zillow/place.py", line 15
    print "%s: %s" % (i, self.__dict__[i])
                 ^
SyntaxError: invalid syntax

**Comment by beardlesslumberjack** [comment]
Hey, i'm running into the same problem, did you ever find out what the issue was?

**Comment by JJ0131** [comment]
Nope. I used another zillow package.

**Comment by beardlesslumberjack** [comment]
which one did you use?

**Comment by JJ0131** [comment]
I'm sorry I just checked my old scripts. I used the same package but looks like I installed python 2.7 just for this package LOL.

**Comment by KixS** [comment]
There is an easy fix. Open the file place.py and put between brackets the print argument. 

Python 3 changed the print syntax.

```
Python 2 : print xxxx
Python 3: print(xxxx)
```

**Comment by JJ0131** [comment]
KixS,

You are definitly correct. Did you try this approach? I didn't do it simply because I was concerned there might be some other stuff not compatible with 3.x.

**Comment by KixS** [comment]
Yes, I just installed the module and so far it works as expected with Python 3.6

**Comment by JJ0131** [comment]
Perfect. Thank you KixS.
